site_name: FIWARE IoT Broker
#site_url: 
repo_url: https://github.com/Aeronbroker/Aeron.git
site_description: IoT Broker documentation
docs_dir: doc/
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
#extra_css: ["http://fiware.org/style/monokai_sublime.css"]
pages:
  - Installation and Administration Guide: installadminguide.md